[project]
name = "ml-pytorch-detectron"
version = "0.1.0"
description = ""
authors = [
    {name = "Petr Pokorný",email = "petr.pokorny@bighub.cz"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "torch (>=2.9.0,<3.0.0)",
    "torchvision (>=0.24.0,<0.25.0)"
]

[tool.poetry]
packages = [{include = "ml_pytorch_detectron", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
